# Generated by Django 4.2.5 on 2023-09-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='lesson',
            field=models.ManyToManyField(to='lessons.lesson'),
        ),
    ]
